### ISSUE TITLE
Ip2366 on this board

### ISSUE THREAD

**Issue by sheedyaja** [D-314/IP2368-Arduino-Library#10]
![Screenshot_20241211_065340](https://github.com/user-attachments/assets/ed14cc26-f3b9-41f7-80c4-f96e6c65b4f0)
![Screenshot_20241211_065444](https://github.com/user-attachments/assets/6692db46-048a-4ff2-b5b1-b76e586204eb)

This is a IP2366 based power/charger module
Any possibilities for this codes to work on that board?

**Comment by D-314** [comment]
@pls share BOM file. It is difficult to see the chip label in the photo you provided

**Comment by D-314** [comment]
@sheedyaja, okay, based on the components, the schematic seems similar to the IP2366. You can desolder these resistors (see the attached image) and use the points where they were connected as `I2C_SCL`, `I2C_SDA`, and `I2C_INT`

![{673A38FE-0C16-4A6E-AD14-8ACE12D92477}](https://github.com/user-attachments/assets/28d637c7-8dd3-4496-ba23-8a62067db531)

However, be cautious—this might be a revision of the IP2366 that does not support I2C (previously discussed in [issue #3](https://github.com/D-314/IP2368-Arduino-Library/issues/3)).  

That said, if you're lucky, you can use this library with your board.

**Comment by sheedyaja** [comment]
@D-314 will try tomorrow, thanks

**Comment by sheedyaja** [comment]
@D-314 update, it doesn't work

**Comment by D-314** [comment]
@sheedyaja, could you please share a photo with your connections?
