### ISSUE TITLE
Posting trash data when no chip connected

### ISSUE THREAD

**Issue by daskalovst** [D-314/IP2368-Arduino-Library#2]
Battery Percentage [%]: 255
Battery Voltage [mV]: 65535
1
1
1
Unknown Charge State

it needs to have some check is it connected before starts sending requests

**Comment by D-314** [comment]
It looks like a communication error. The function returns a value in any case, even if the request is unsuccessful. In the specific example, 0xFF (255) is returned as an error code, and 0xFFFF (65535), as two two bytes received with an error or not received at all.
