### ISSUE TITLE
SetMaxOutputPower() not allowing for high power setting.

### ISSUE THREAD

**Issue by rmarket6** [D-314/IP2368-Arduino-Library#9]
Attempting to set the maximum power out by using the setMaxOutputPower() function, and then reading from the getMaxOutputPower() function returns the incorrect value only when I attempt to set the maximum power out to W100 or W140. Every other setting allows me to set it (W30 - W65). 

`deviceA.setMaxOutputPower(IP2366::Vbus1OutputPower::W140, err);`
 ` Serial.print("max output pwoer:1 ");`
  `delay(200);` 
  `IP2366::Vbus1OutputPower x = deviceA.getMaxOutputPower(err);`
  `switch(x)`
  `{`
    `case (IP2366::Vbus1OutputPower::W30):`
    `Serial.println("W30");`
    `break;`
    `case IP2366::Vbus1OutputPower::W45:`
    `Serial.println("W45");`
    `break;`
    `case IP2366::Vbus1OutputPower::W60:`
    `Serial.println("W60");`
    `break;`
    `case IP2366::Vbus1OutputPower::W65:`
    `Serial.println("W65");`
    `break;`
    `case IP2366::Vbus1OutputPower::W100:`
    `Serial.println("w100");`
    `break;`
    `case IP2366::Vbus1OutputPower::W140:`
    `Serial.println("W140");`
    `break;`
  `}`
  `delay(100); `

**Comment by D-314** [comment]
@rmarket6,
